pipeline {
    agent any

    stages {
        stage("Build") {
            steps {
                echo "Building.."

                dir("${WORKSPACE}/coding/twitter-fire-scraper-webapi/") {
                    bat "ruby build.rb"
                }
            }
        }
        stage("Test") {
            steps {
                echo "Testing.."

                dir("${WORKSPACE}/coding/twitter-fire-scraper-webapi/") {
                    bat "ruby test-localwheel-install.rb"
                }
            }
        }
    }
    post {
        always {
            echo "Cleaning..."
            
                dir("${WORKSPACE}/coding/twitter-fire-scraper-webapi/") {
                bat "ruby clean.rb"
            }
        }
    }
}
